server:
  port: 8081
  servlet:
    context-path: /

spring:
  datasource:
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/cloud_user?useUnicode=true&characterEncoding=utf-8
      username: root
      password: root
      # 监控统计拦截的filters
      filters: stat,wall
      #配置初始化大小/最小/最大
      initial-size: 10
      min-idle: 10
      max-active: 60
      #获取连接等待超时时间
      max-wait: 60000
      # 默认自动提交
      default-auto-commit: true
      #一个连接在池中最小生存的时间
      min-evictable-idle-time-millis: 60000
      #间隔多久进行一次检测，检测需要关闭的空闲连接
      time-between-eviction-runs-millis: 3600000
      validation-query: SELECT 1 FROM DUAL
      test-while-idle: true
      test-on-borrow: true
      test-on-return: true
      #打开PSCache，并指定每个连接上PSCache的大小。oracle设为true，mysql设为false。分库分表较多推荐设置为false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: 20
